let assetPaths = [
  {"path":"material/air.png"},
  {"path":"dead.png"},
  {"path":"player/fall/1.png"},
  {"path":"player/idle/1.png"},
  {"path":"player/idle/2.png"},
  {"path":"player/jump/1.png"},
  {"path":"player/run/1.png"},
  {"path":"player/run/2.png"},
  {"path":"player/skins/base.png"},
  {"path":"player/skins/cowboy.png"},
  {"path":"player/skins/green.png"},
  {"path":"player/skins/king.png"},
  {"path":"player/skins/kingking.png"},
  {"path":"player/skins/ninja.png"},
  {"path":"player/skins/shrek.png"},
  {"path":"player/wall/1.png"},
  {"path":"player/idle.anim"},
  {"path":"player/run.anim"},
  {"path":"rooms/00 Test Room.ob"},
  {"path":"key.png"},
  {"path":"door/1.png"},
  {"path":"door/2.png"},
  {"path":"door/3.png"},
  {"path":"door/4.png"},
  {"path":"door/5.png"},
  {"path":"door/6.png"},
  {"path":"door/7.png"},
  {"path":"door.anim"},
  {"path":"rooms/01 Test Room.ob"},
  {"path":"rooms/02 Test Room.ob"},
  {"path":"rooms/03 Test Room.ob"},
  {"path":"rooms/04 Nils Hus.ob"},
  {"path":"rooms/05 The End.ob"},
  {"path":"winscreen.ob"}
];
let scenePaths = ["SceneEditor","SceneGame","SceneLevelPicker","SceneMainMenu","SceneSettings"];
